### ISSUE TITLE
Epic: Create a 'Contact' page

### ISSUE THREAD

**Issue by Jaywesterlow** [Jaywesterlow/QC-Motor-Techniek#4]
# Contact

- [ ] Locatie, email en telefoonnummer
- [ ] openingstijden en korte invullijst om contact op te nemen (Could)
- [ ] ingeladen google maps kaart met locatie
